### PR TITLE
Map max sampler anisotropy

### LINKED ISSUE #157: maxSamplerAnisotropy in VkPhysicalDeviceLimits is 0
This value should be initialized to something sensible since anisotropic filtering is claimed to be supported by setting VkPhysicalDeviceFeatures::samplerAnisotropy to 1.

### PR DESCRIPTION
**Pull request by grovesNL**
Fixes #157

### CODE REVIEW

**Comment by kvark** [comment]
Added the update commit myself :)
bors r+

**Comment by zeux** [comment]
Thanks! Does anything special need to happen to get a new release? I think the binary on the GH release doesn't have this change yet.

**Comment by kvark** [comment]
@zeux we'll make a release (shortly!) once #162 lands

**Comment by kvark** [comment]
@zeux it should be included in https://github.com/gfx-rs/portability/releases/tag/0.1

**Pull request merged**
