### PR TITLE
Port to the new swapchain model

### LINKED ISSUE #208: Support the new gfx-hal swapchain model
This is a tough thing to get, but if we succeed, it would allow gfx-hal to completely remove the old swapchain implementation, which means cleaning up a lot of tricky code.

### LINKED ISSUE #212: Support VK_KHR_get_surface_capabilities2

### PR DESCRIPTION
**Pull request by kvark**
Closes #208
Fixes #212 
Also has general fixes to:
  - push constant offsets in `gfxCreatePipelineLayout`
  - destination subresources in `gfxCmdResolveImage`

The PR is inviting for discussion: @grovesNL @msiglreith 
I'm not 100% sure what to do yet.

The Good:
  1. Being able to remove the old swapchain from gfx-rs COMPLETELY. It was hacky on all the backends other than Vulkan, quite complicated on Metal, and didn't work very in general.
  2. Fullscreen support! It's not ideal yet (occasional hitches), but it was pretty much non-functional before. In general, stuff that runs is more robust this change.

The Bad:
  1. Portability implementation is a bit more complex now, but not extraordinary so. In general, I think it's a win if we move some complication out of gfx-rs into gfx-portability, since gfx-rs has more users, it's more important to keep clean.
  2. We can't support recording a render pass that uses a swapchain image if either:
    - the image is not acquired at the moment of recording
    - the command buffer is re-usable. We expect the users to strictly acquire-record-submit-present.

The Ugly:
  1. Our KHR swapchain implementation is more limited: no support for any usage other than COLOR_ATTACHMENT. This is technically valid in Vulkan, but for some reason many apps expect to transfer to/from swapchain images. So this is fine for the matter of CTS and VkPI, but can introduce some friction in real world testing.
  2. The new swapchain model itself needs to be evolved a bit more, according to https://github.com/gfx-rs/gfx/issues/3184 . We don't know how exactly: there is both a risk (that we'll need to redo something here) and an opportunity (that we'll support other usages, for example).

### CODE REVIEW

**Comment by kvark** [comment]
I suppose one thing we'd want to know is the full extent of incompatibility that this PR would set. I'll try to get a sense of it by going through the rest of apps in #125 . If Dota2 keeps vendor-locking (see https://github.com/ValveSoftware/Dota-2/issues/1727), I'll consider implementing this call in here :/

**Comment by msiglreith** [comment]
How does this interact with present modes? In particular, out of order presentation and acquiring multiple swapchain images?

**Comment by kvark** [comment]
> out of order presentation

Should be unaffected.

> acquiring multiple swapchain images

multiple images of the same swapchain - not supported by this path

**Comment by kvark** [comment]
Given the amount of testing I'm doing right now, will be confident to release portability-0.8 right after this merges, if we proceed 😄

**Comment by kvark** [comment]
We can't hold this off forever.
bors r+

**Comment by kvark** [comment]
bors retry

**Pull request merged**
